
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class CharcClassGrowth : Luban.BeanBase
{
    public CharcClassGrowth(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ClassName = _buf.ReadString();
        StrChanceMin = _buf.ReadInt();
        StrChanceMax = _buf.ReadInt();
        AgiChanceMin = _buf.ReadInt();
        AgiChanceMax = _buf.ReadInt();
        IntChanceMin = _buf.ReadInt();
        IntChanceMax = _buf.ReadInt();
    }

    public static CharcClassGrowth DeserializeCharcClassGrowth(ByteBuf _buf)
    {
        return new CharcClassGrowth(_buf);
    }

    /// <summary>
    /// ##职业ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// ##职业名称
    /// </summary>
    public readonly string ClassName;
    /// <summary>
    /// ##力道概率区间下限(%)
    /// </summary>
    public readonly int StrChanceMin;
    /// <summary>
    /// ##力道概率区间上限(%)
    /// </summary>
    public readonly int StrChanceMax;
    /// <summary>
    /// ##身法概率下限
    /// </summary>
    public readonly int AgiChanceMin;
    /// <summary>
    /// ##身法概率上限
    /// </summary>
    public readonly int AgiChanceMax;
    /// <summary>
    /// ##悟性概率下限
    /// </summary>
    public readonly int IntChanceMin;
    /// <summary>
    /// ##悟性概率上限
    /// </summary>
    public readonly int IntChanceMax;
   
    public const int __ID__ = 1902157682;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "className:" + ClassName + ","
        + "strChanceMin:" + StrChanceMin + ","
        + "strChanceMax:" + StrChanceMax + ","
        + "agiChanceMin:" + AgiChanceMin + ","
        + "agiChanceMax:" + AgiChanceMax + ","
        + "intChanceMin:" + IntChanceMin + ","
        + "intChanceMax:" + IntChanceMax + ","
        + "}";
    }
}
}

