
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbCharcClassGrowth
{
    private readonly System.Collections.Generic.Dictionary<int, CharcClassGrowth> _dataMap;
    private readonly System.Collections.Generic.List<CharcClassGrowth> _dataList;
    
    public TbCharcClassGrowth(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CharcClassGrowth>(n);
        _dataList = new System.Collections.Generic.List<CharcClassGrowth>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CharcClassGrowth _v;
            _v = global::GameConfig.CharcClassGrowth.DeserializeCharcClassGrowth(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, CharcClassGrowth> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharcClassGrowth> DataList => _dataList;

    public CharcClassGrowth GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharcClassGrowth Get(int key) => _dataMap[key];
    public CharcClassGrowth this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

